### ISSUE TITLE
Provided API key is invalid for this endpoint

### ISSUE THREAD

**Issue by vikpande** [magiclabs/magic-near-guide#14]
Team, I get the following error when i try to build and test a NEAR app with Magic 👍 

"_Provided API key is invalid for this endpoint"_. can you please assist? Thank you. 

<img width="1221" alt="image" src="https://github.com/magiclabs/magic-near-guide/assets/15668152/6fa89147-4e43-4b74-badb-9b16666ac425">

**Comment by vikpande** [comment]
@hcote , SOS :-)

**Comment by bhalsodkhushal** [comment]
@vikpande You are getting the error because you are using a Magic Connect API key and are calling the login method for a Magic Auth app. The resolution is for you to use a Magic Auth API key.

**Comment by vikpande** [comment]
Yes. Thanks much. Got this fixed. Also the oauth piece. Appreciate it.
